### ISSUE TITLE
Custom app doesn't work.

### ISSUE THREAD

**Issue by IMCraytex** [luxu-gg/okokphone_custom_app#1] opened 2024-04-28 11:54 UTC
So the issue all comes down to the fact in the original okokPhone script the cfx url is hardcoded (or atleast seems to be hardcoded) to be "https://cfx-nui-custom_app/web/app.html" No matter what I change in the resource. It does work if the resource is called custom_app obviously

**Comment by luxu-gg** [comment] 2024-04-28 12:29
The issue seems to be originating from the hardcoded variables in utils.js

```js
const resourceName = "custom_app";
const appName = "custom_app";
```

I will try a better way

**Comment by IMCraytex** [comment] 2024-04-28 12:34
So i did try change that but it still points to the custom_app page

**Comment by luxu-gg** [comment] 2024-04-28 14:42
> So i did try change that but it still points to the custom_app page

Your correct, the issue is comming from the phone itself.
Will be fixed on 0.1.0.

I will also update this repo with more instructions.

**Comment by luxu-gg** [comment] 2024-04-28 15:41
check commit b3d1708

**Comment by IMCraytex** [comment] 2024-04-28 18:14
Glad to hear the issue will be fixed, Appreciate all your help here. Any eta on when we can be expecting 0.1.0?

**Comment by luxu-gg** [comment] 2024-04-28 20:31
In a few days

**Closed as completed** 2024-04-29 11:23 UTC
